source("partiplott.R")
lapply(as.vector(Partiliste$Parti),partiplott)
## partiplott(fork="A")
## partiplott(fork="SV")
## partiplott(fork="RV")
## partiplott(fork="SP")
## partiplott(fork="KRF")
## partiplott(fork="V")
## partiplott(fork="H")
## partiplott(fork="FRP")
## partiplott(fork="DEM")
## partiplott(fork="DLF")
## partiplott(fork="KSP")
## partiplott(fork="KYST")
## partiplott(fork="MDG")
## partiplott(fork="NKP")
## partiplott(fork="PP")
## partiplott(fork="SFP")
## partiplott(fork="TPF")
## partiplott(fork="ABORT")
## partiplott(fork="ES")
## partiplott(fork="NPAT")
## partiplott(fork="NRA")
## partiplott(fork="SALL")
## partiplott(fork="SAMT")
## partiplott(fork="VIGRID")
